{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "todoapp.fullname" . }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: "{{ include "todoapp.name" . }}"
{{- end }}