replicaCount: 1

image:
  repository: raimundas0106/rocket
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: todo.devplay.art
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}